# Uncomment the next line to define a global platform for your project
use_frameworks!
use_modular_headers!

platform :ios, '12.0'

target 'sample_ios' do
  pod 'FirebaseAnalytics'
  pod 'common', :path => '../common/'
end
